services:
  fastapi-teuxdeux:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-teuxdeux-dev
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/app/data/teuxdeux.db
    volumes:
      # Persist the SQLite database
      - ./data:/app/data
      # Persist logs (optional)
      - ./logs:/app/logs
      # Copy static files from the current project
      - ./static:/app/static:ro
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
    driver: local
  logs:
    driver: local