services:
  teuxdeux:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teuxdeux-clone
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=release
      - DB_PATH=/app/data/teuxdeux.db
    volumes:
      # Persist the SQLite database
      - ./data:/app/data
      # Persist logs (optional)
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy (uncomment if needed)
  # nginx:
  #   image: nginx:alpine
  #   container_name: teuxdeux-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - teuxdeux
  #   restart: unless-stopped

volumes:
  data:
    driver: local
  logs:
    driver: local